### ISSUE TITLE
Specific pages from mozilla.org that should be available in Reader View, in fact aren't

### ISSUE THREAD

**Issue by avaida** [mozilla/readability#122]
**Affected branches**:
Nightly 40.0a1 (2015-04-07), Aurora 39.0a2 (2015-04-07), Beta 38.0b2-build1 (20150406174117)

**Sample page showing this issue**:
https://www.mozilla.org/en-US/mission/

**Comment by gijsk** [comment]
Why "should" be available in reader view?

**Comment by avaida** [comment]
I believe it "should" be available because it's a simple page with a few paragraphs and a headline, but I'm not sure exactly what makes a page compatible with Reader View or not.

**Comment by n1k0** [comment]
> I'm not sure exactly what makes a page compatible with Reader View or not.

That's a good point, we don't have a good definition of what "readerable" actually means precisely.

**Comment by gijsk** [comment]
I'm going to go out on a limb and say that because it's not an article/blogpost-type thing and doesn't have a great deal of scrollable text content, it's OK that this isn't readerable.

I actually think "simple page" is somewhat of a counterargument, even: reader mode is supposed to help with somewhat-long-form text that's embedded in visually noisy pages. Simple pages with a few paragraphs and a headline are neither of those things.

I wouldn't be very fussed either way, but it doesn't seem helpful to invest a lot of time into making this readerable when we have issues with things that clearly *are* articles that ought to be readerable, so I'm going to close this without taking further action to fix.
