### ISSUE TITLE
Firefox offers Reader View for hg pushlogs

### ISSUE THREAD

**Issue by rvandermeulen** [mozilla/readability#13]
When I open https://hg.mozilla.org/integration/gaia-2_2/pushloghtml, I get the Enter Reader View icon in the location bar, which is a bit of an interesting choice :)

**Comment by fwenzel** [comment]
Doesn't it offer reader mode for any site?

**Comment by leibovic** [comment]
No, only for sites where we detect an article. For example, we don't offer it on the google.com homepage.

In general, it's probably better to err on the side of showing it when the user doesn't want it, rather than *not* showing it when the user does, so we should just be careful not to regress anything if we're more aggressive about our "not an article" logic.

**Comment by gijsk** [comment]
This is fixed with our newer detection logic.
