### ISSUE TITLE
Pages from techcrunch.com are partially missing byline information in Reader View

### ISSUE THREAD

**Issue by avaida** [mozilla/readability#153]
**Affected**:
- 38.0b5-build1
- 39.0a2 (2015-04-16)
- 40.0a1 (2015-04-16)

**Sample pages**:
- http://techcrunch.com/2015/04/16/microsoft-and-yahoo-renew-search-allian/
- http://techcrunch.com/2015/04/16/etsy-stock-surges-86-percent-at-close-of-first-day-of-trading-to-30-per-share/

**Notes**:
For example, the first sample is missing one of the authors, "Sarah Perez".

**Comment by leibovic** [comment]
It looks like there are 2 author meta tags, but right now we only expect there to be one:
https://github.com/mozilla/readability/blob/master/Readability.js#L920

Instead of just setting metadata.byline, we should probably concatenate additional authors if we see more author tags (although doing this in an l10n friendly way might be hard).

**Comment by gijsk** [comment]
This looks better now.
