### ISSUE TITLE
Parts of the headline are missing in Reader View for pages from webmd.com

### ISSUE THREAD

**Issue by avaida** [mozilla/readability#174]
**Affected**:
* 38.0b6-build1 (20150420134330)
* 39.0a2 (2015-04-20)
* 40.0a1 (2015-04-20)

**Sample page showing this issue**:
http://www.webmd.com/news/20150417/superbugs-what-they-are

**Notes**:
The headline for the sample is:
> Superbugs: What They Are and How You Get Them

but *Superbugs:* is missing from it in Reader View.

**Comment by n1k0** [comment]
This is because we assume titles containing a colon (`:`) should have whatever before it being stripped out:

```js
    } else if (curTitle.indexOf(': ') !== -1) {
      curTitle = origTitle.replace(/.*:(.*)/gi, '$1');
```

We don't distinguish between titles like `WebsiteName: Article goes here` and `Superbugs: What They Are and How You Get Them`. I think this rule is too aggressive, I suggest we drop it entirely.
