### ISSUE TITLE
Bad readability on Google search results

### ISSUE THREAD

**Issue by AaronMT** [mozilla/readability#253]
![screen shot 2015-10-20 at 1 54 34 pm](https://cloud.githubusercontent.com/assets/102331/10616231/1a53e454-7732-11e5-8a21-0a38200c8e01.png)

**Comment by gijsk** [comment]
Is this on iOS? We don't even offer reader mode on desktop.

**Comment by AaronMT** [comment]
This is iOS

**Comment by gijsk** [comment]
TBH it's probably worth filing a bug against the iOS integration of reader mode (in bugzilla or somewhere else on github), because whatever they're doing, it's different from desktop and android, neither of which offers reader mode for the google search results page. So it seems unlikely to be an actual readability bug that we can fix by a change in this repo.
