### ISSUE TITLE
Bad readability detection when no filename/dirname in URI

### ISSUE THREAD

**Issue by timovn** [mozilla/readability#261]
Hi,

I have some problems on my sites when the url has no filename in it.
For instance, these does work :
http://example.com/index.php?param
http://example.com/directory/?param
But this does not :
http://example.com/?param

Here is a real live example : 
Does Work : http://couleur-science.eu/index.php?d=2016/01/11/05/27/02-
Does not work : http://couleur-science.eu/?d=2016/01/11/05/27/02-

The previous domain (couleur-science.eu) is hosted on the same server as http://lehollandaisvolant.net , at this path: http://lehollandaisvolant.net/couleur-science.eu 

When I access it from couleur-science.eu, icon does not show up.
When I access it from http://lehollandaisvolant.net/couleur-science.eu , icon shows up.

As for that example, I have a redirection that is active, though. I can turn it off temporarily if you need.

The HTML code is exactly the same in theses cases.

I also tested the standalone Readability.js and it works : the DOM is succesfully parsed and the good article/data is extracted.

So it is probably only a URI-parsing problem (but a problem nevertheless).
Maybe a conflict with a $path that is empty when parsing the URI?

**Comment by gijsk** [comment]
> When I access it from couleur-science.eu, icon does not show up.
> When I access it from http://lehollandaisvolant.net/couleur-science.eu , icon shows up.

Firefox filters out "homepages" (ie URLs with no path) to avoid false positives. It is unlikely that this will change, sadly. Making a full determination of whether a page is readable is quite costly, and doing it on sites that are practically very unlikely to contain an article or something like it isn't worth that cost. So we use a much simpler mechanism, which would likely flag many homepages as "seems to have enough `<p>` tags to have an article" when really, they're not articles. So we filter out homepages.

I expect that this is also affecting your other example, because we ignore query strings when making this determination. Many sites, including but not limited to: Google, Yahoo, Facebook, ... will redirect to a URL with a query string automatically when accessing the root domain.

Note that all of this logic is inside Firefox, not inside the readability library in this github repo - you could use the library and it would work perfectly well on all of these pages, irrespective of the URL.

If you have suggestions about what to do here without causing performance loss, do let us know. :-)

**Comment by timovn** [comment]
Ok, so the problem lies with Firefox.
Yes, I saw that my HTML code did work correctly with the standalone readability lib.

For a suggestion, I often work on avoiding useless CPU solicitations.

I didn’t yet read the JS code entirely, but as I understand, the current lib parses the whole page and then determines if it is worth showing a icon or not, by using a "score".
Why not parse the page gradually and put a breakpoint once you are sure the article contains enough `<p>` tags (or other stuff) ? With this, you could calculate the score live, not after having the whole page being parsed (as I said, I might not be aware if this is already the case, but it might help quite drastically).

Another thing to do might be to clean the page before the analysis (avoiding parsing elements that would eventually be removed, wasting CPU time).
Script tags and so on should be removed at the beginning of the script. `.comment`, `<form>`, `<footers>` and other irrelevant stuff too. Then, remove all the CSS tree, the classes, the events, and then only start scoring the page : if the DOM tree is lighter, parsing it will go faster (and will be better for memory too).

Finally, if a document has only a sole `<article>`, you could consider it as the relevant data. If not, there could be a fallback where the entire page is parsed and scored.
This would lead to more JS-code, but it is usually much faster to use longer code with more if/else cases.

**Comment by gijsk** [comment]
In the Firefox case, we go from the Gecko DOM as available for DOMContentLoaded to determine if the page can be rendered in reader mode. We don't actually use `_parse` because it modifies the DOM, and so to use the DOM we'd need to clone it, which is expensive. See this code: https://github.com/mozilla/readability/blob/master/Readability.js#L1704 .

Removing CSS classes and so on breaks things because we shouldn't take hidden things into account, and unfortunately there is a lot of content out there (cf. this bug https://bugzilla.mozilla.org/show_bug.cgi?id=1230050 ) that includes stuff that is display: none that we need to ensure we don't include as part of the readerable content.

Some of the suggestions you're making amount to rearchitecturing the entire codebase, which would take a lot of time and where it would be hard to ensure that results would be on par or better with the current codebase. Others we already do (like stripping `<script>`).

**Comment by gijsk** [comment]
Going to close this out in favour of https://bugzilla.mozilla.org/show_bug.cgi?id=1261540 .
