### ISSUE TITLE
_getAllNodesWithTag() method fallback returns HTMLCollection array

### ISSUE THREAD

**Issue by mcapella** [mozilla/readability#287]
It seems that _getAllNodesWithTag() uses node.querySelectorAll() for browsers that support it, which I'd assume are all at this point.

The fallback use of node.getElementsByTagName() returns an array of HTMLCollection items, vs nodes.

If moz used that fallback, the main consumer of the method isProbablyReaderable() would have issues, failing in the visibilityHelper:
Error: "NS_ERROR_XPC_BAD_CONVERT_JS: Could not convert JavaScript argument arg 0 [nsIDOMWindowUtils.getBoundsWithoutFlushing]" {file: "resource://gre/modules/ReaderMode.jsm" line: 140}]
ReaderMode.isNodeVisible() calls |... utils.getBoundsWithoutFlushing(node);|

If we need to keep the fallback, it seems the proper way to retrieve and flatten the node array is:

return [].concat.apply([], tagNames.map(tag => {
      return [].slice.call(node.getElementsByTagName(tag));
}));

**Comment by gijsk** [comment]
We do use the fallback with JSDOMParser, "even" in Gecko browsers, because JSDOMParser doesn't support querySelectorAll... And it works fine, presumably because `Array.concat`'s behaviour is different if you pass it arrays instead of HTMLCollections. We should probably detect that. And we should use `Array.from()` instead of `[].slice`.
