### ISSUE TITLE
I have no idea about JSDOMParser.js 

### ISSUE THREAD

**Issue by rupertqin** [mozilla/readability#327]
JSDOMParser.js， as I see, just for test's purpose, so why join to this module.

And the doc's Usage example:
```js
var loc = document.location;
var uri = {
  spec: loc.href,
  host: loc.host,
  prePath: loc.protocol + "//" + loc.host,
  scheme: loc.protocol.substr(0, loc.protocol.indexOf(":")),
  pathBase: loc.protocol + "//" + loc.host + loc.pathname.substr(0, loc.pathname.lastIndexOf("/") + 1)
};
var article = new Readability(uri, document).parse();
```
 the `uri` struct is useless as I see,  just confuse us.

**Comment by gijsk** [comment]
> JSDOMParser.js， as I see, just for test's purpose, so why join to this module.

Firefox for desktop and Firefox for Android use it because they run readability in a worker thread (which has no real DOM to use). So we run tests with it to ensure things work correctly.

> And the doc's Usage example:
> ```js
> var loc = document.location;
> var uri = {
>   spec: loc.href,
>   host: loc.host,
>   prePath: loc.protocol + "//" + loc.host,
>   scheme: loc.protocol.substr(0, loc.protocol.indexOf(":")),
>   pathBase: loc.protocol + "//" + loc.host + loc.pathname.substr(0, loc.pathname.lastIndexOf("/") + 1)
> };
> var article = new Readability(uri, document).parse();
> ```
> the `uri` struct is useless as I see,  just confuse us.

The `uri` struct is used to process relative links in the document. So if the document you're parsing contains:

`<a href="foo.html">Link</a>`

Then the result from readability will contain an absolute href attribute (so that you can include it in pages that might have a different URL without the links being broken).
