### ISSUE TITLE
Is it possible to extract text from local html instead of providing a public link?

### ISSUE THREAD

**Issue by vitaly-zdanevich** [mozilla/readability#389]
Yes or not - please mention this in README - because this is a common case, I think.

**Comment by gijsk** [comment]
I don't really understand the question. `Readability` itself takes a DOM object, and how you obtain that (from a local file or a public link) is your business. You pass it a URL to use as the 'base' for rewriting links, so you could either pass an original http: based URL (even if you were using local HTML, maybe you know you downloaded it from somewhere) or you could use a file: based URL.

I expect you're using some other tool than the library itself, and this issue should be filed there instead of here, but maybe I just don't understand what you're getting at.
