### ISSUE TITLE
Uncaught DOMException on https://losst.ru/obnovlenie-debian-9

### ISSUE THREAD

**Issue by rNeomy** [mozilla/readability#392]
I am getting

```
Uncaught DOMException: Failed to execute 'setAttribute' on 'Element': 'adsbygoogle.js"' is not a valid attribute name.
    at Readability._setNodeTag (Readability.js:477:19)
    at Readability._grabArticle (Readability.js:774:25)
    at Readability.parse (Readability.js:2062:31)
    at 
```

which refers to

```js
  _setNodeTag: function (node, tag) {
    this.log("_setNodeTag", node, tag);
    if (node.__JSDOMParser__) {
      node.localName = tag.toLowerCase();
      node.tagName = tag.toUpperCase();
      return node;
    }

    var replacement = node.ownerDocument.createElement(tag);
    while (node.firstChild) {
      replacement.appendChild(node.firstChild);
    }
    node.parentNode.replaceChild(replacement, node);
    if (node.readability)
      replacement.readability = node.readability;

    for (var i = 0; i < node.attributes.length; i++) {     /*the next line*/
      replacement.setAttribute(node.attributes[i].name, node.attributes[i].value);
    }
    return replacement;
  },

```

**Comment by gijsk** [comment]
Can you provide more detailed STR? If I open the page in Firefox and enter reader mode, it works. What are you doing differently?

**Comment by rNeomy** [comment]
I am porting this to Chrome. To regenerate you can follow this

1. Open the page in Chrome
2. Open dev tools
3. Paste the latest Readability.js
4. paste this code
```js
var loc = document.location;
var uri = {
  spec: loc.href,
  host: loc.host,
  prePath: loc.protocol + '//' + loc.host,
  scheme: loc.protocol.substr(0, loc.protocol.indexOf(':')),
  pathBase: loc.protocol + '//' + loc.host + loc.pathname.substr(0, loc.pathname.lastIndexOf('/') + 1)
};

var documentClone = document.cloneNode(true);
var article = new Readability(uri, documentClone).parse();

var iframe = document.createElement('iframe');
document.body.appendChild(iframe);
iframe.contentDocument.open();
iframe.contentDocument.write(article.content);
iframe.contentDocument.close();
```

which causes:

```
Uncaught DOMException: Failed to execute 'setAttribute' on 'Element': 'adsbygoogle.js"' is not a valid attribute name.
    at Readability._setNodeTag (<anonymous>:477:19)
    at Readability._grabArticle (<anonymous>:774:25)
    at Readability.parse (<anonymous>:2062:31)
    at <anonymous>:11:51
```

**Comment by gijsk** [comment]
I can no longer reproduce this with the latest version of Readability and Chrome, so I assume this has been fixed since. :-)

**Comment by MrOrz** [comment]
@gijsk I can reproduce the `Uncaught DOMException: Failed to execute 'setAttribute' on 'Element'` error on different pages.

Here are the reproduction steps:

1. Visit https://opinion.udn.com/opinion/story/10124/3561413 on Google Chrome
2. Open Devtool JS console
3. paste in latest readability.js
4. execute `new Readability(location.href, document).parse();`

Expected: article being parsed
Actual: thown error `Uncaught DOMException: Failed to execute 'setAttribute' on 'Element': '0' is not a valid attribute name.`

I have a bunch of URLs that can be used to reproduce the above behavior:
https://docs.google.com/spreadsheets/d/1TwDZmocHxlcSPm2zQoGJF167Uj9RNgqHREEx3PEa580/edit?usp=sharing

Apparently it's caused by malformed HTML, but it should not crash the entire readability.

**Comment by gijsk** [comment]
Well, this is fun... I filed https://github.com/whatwg/html/issues/4275 for the inconsistency between how HTML is parsed and how the DOM APIs validate exactly the same thing. I should have a patch for this using the workaround mentioned there (using `element.attributes.setNamedItem()` instead of `element.setAttribute()`).

**Comment by gijsk** [comment]
Yum, and `cloneNode()` is not supported for `Attr` in jsdom... https://github.com/jsdom/jsdom/issues/2478

**Comment by gijsk** [comment]
OK, so maybe the simpler solution is just to ignore those additional attributes that we can't even set; it's not like we need them for anything...

**Comment by gijsk** [comment]
OK, so PR is up, as well as issues found in `jsdom` and HTML/DOM as a result. Thanks @MrOrz for the clear steps to reproduce!
