### ISSUE TITLE
Scale text in <pre> tags to fit horizontally

### ISSUE THREAD

**Issue by PrototypeNM1** [mozilla/readability#417]
Reader mode often mangles code samples which are wrapped \<pre\> tags, making the sample very difficult to read.

Examples:
http://blog.mbrt.it/2016-12-01-ripgrep-code-review/
https://bojandjurdjevic.com/2018/WASM-vs-JS-Realtime-pitch-detection/

It would help in the cases if the text were scaled to fit horizontally, thus retaining indentation.

**Comment by gijsk** [comment]
Can you explain what you mean more fully, perhaps with a screenshot of what you're seeing? I don't see any issues looking at your examples off-hand, but it might be to do with the line width I have set in my Firefox copy ([Aa] button, then the ones with arrows). Perhaps those could help you work around the issue?

(Technically, this repository doesn't contain the CSS for Firefox's reader mode, only the JS bits, and so I'll need to file this on bugzilla anyway, but let's figure out the details of what the issue is first)

**Comment by PrototypeNM1** [comment]
![image](https://user-images.githubusercontent.com/2732021/35457684-c6506f18-02a7-11e8-83b4-907d12826554.png)
![image](https://user-images.githubusercontent.com/2732021/35457722-e56daa50-02a7-11e8-9eec-c3a6e9602c2d.png)

A combination of reducing the text size and expanding line widths works. The default settings in FF often mangles code due to word wrapping and it would be nice if this was accounted for; in my use case I'm printing the documents to OneNote in batches and would have to visually inspect every document. On review though I'm not sure that would be in-scope for the project (sorry that the title's a bit of an XY Problem).

**Comment by gijsk** [comment]
Thanks for the clarification! Apologies that it's taken a bit to get back to this. I filed a bug on Firefox's bugtracker ( https://bugzilla.mozilla.org/show_bug.cgi?id=1433920 ) to try to address this with some styling in Firefox.
