### ISSUE TITLE
Can I get only the link of the images, if its possible please tell me how? 

### ISSUE THREAD

**Issue by lohenyumnam** [mozilla/readability#426]

**Comment by gijsk** [comment]
You could post-process the document you get back from readability and replace the `<img>` elements with something else. But there's no builtin functionality in the library to do what you want, if that's what you're asking, and it's not clear to me why you would want to do it using Readability rather than by just processing the DOM of the original page yourself.

**Comment by lohenyumnam** [comment]
Thanks for the tips, I did process from the DOM itself and it works
