### ISSUE TITLE
jsdom version issues

### ISSUE THREAD

**Issue by bittlingmayer** [mozilla/readability#444]
As discussed in https://github.com/mozilla/readability/issues/376#issuecomment-385206370, the following code fails:

https://gist.github.com/bittlingmayer/7a14f3a9c17b42163d12ba7da9bd1866

```
	Content.parse( https://www.nzz.ch/international/nahost-und-afrika/komitee-zur-befreiung-der-levante-extremistengruppen-in-syrien-schliessen-sich-zusammen-ld.142403 )
Fetching  https://www.nzz.ch/international/nahost-und-afrika/komitee-zur-befreiung-der-levante-extremistengruppen-in-syrien-schliessen-sich-zusammen-ld.142403
Fetched  https://www.nzz.ch/international/nahost-und-afrika/komitee-zur-befreiung-der-levante-extremistengruppen-in-syrien-schliessen-sich-zusammen-ld.142403
Content._parse(...)
(node:5014) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 1): TypeError: Cannot read property 'firstElementChild' of undefined
(node:5014) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

**Comment by gijsk** [comment]
Thanks for the detailed report! I will try to look at this later today - in meetings for the next few hours. @davidar heads-up that this may be a regression from removing the `uri` parameter. Maybe the stub typing detection I suggested isn't working correctly...

**Comment by gijsk** [comment]
OK, so the issue is that the first parameter you're passing to `Readability`'s constructor is a string.

It used to be that we expected an object with some specific properties. See https://github.com/mozilla/readability/blob/fd1557560add5bf5f926e8f0601d879762ab6367/README.md for the documentation prior to the recent change where we dropped the requirement for a URL. So the change from https://github.com/mozilla/readability/commit/d60184966cc20028ba5c49f640091d1ce050c3f9#diff-04c6e90faac2675aa89e2176d2eec7d8 removed this requirement and does some duck-typing to see if you tried to pass such an object, by checking if your first argument doesn't look like a document, and has a `spec` property. But a string doesn't satisfy that requirement. So it assumes your first argument is a document, and then that obviously breaks because the URI string that your script passes is clearly not a document...

I'm... a bit surprised the code in the gist ever worked, because we used to access properties off that object. In particular, I'd expect all our URL processing would be horribly broken ( https://github.com/mozilla/readability/blob/d598baf02b5a7d803074915095891ae17c70feea/Readability.js#L271 ). If you've stored versions of the result of Readability, I'd expect you'd find places where "undefined" crops up in `href` attributes and such like...

Anyway... I guess we can add a trivial workaround on our side, or you could update your code to just not pass the URI to readability at all, passing only the document object, as is now suggested in the README's Usage section:

```js
var article = new Readability(dom.window.document).parse();
```

should work with current tip (but not with much older versions).

Sorry for the confusion/breakage! Hopefully the library is easier to use now that you don't need to pass a URL at all (we just infer it from the document's URL).

**Comment by bittlingmayer** [comment]
@gijsk Thank you, that did indeed fix it.
