### ISSUE TITLE
conversion of image src from relative URL to absolute URL fails on handelsblatt.com

### ISSUE THREAD

**Issue by bittlingmayer** [mozilla/readability#453]
Running Readability on http://app.handelsblatt.com/finanzen/regierungsbildung-italien-ausverkauf-bei-italien-bonds/22593712.html?ticket=ST-534325-tFfHuseMqx0SbbeqMedQ-ap4 yields elements like:

```
<img src="/images/transp/7252108/1-formatOriginal.png" alt="Die europakritische Koalition in Italien beunruhigt Anleiheinvestoren. dpa" />
```

I recently added mobile user agent, it could be that the subdomain `app.` somehow leads to the problem.

**Comment by gijsk** [comment]
Fetching this site through readability or curl gets me 302 authentication redirects to a single-signon page (even when adding a UA header), so I had to save the testcase manually and then fix the HTML, but I get the following markup out of readability:

https://gist.github.com/gijsk/a36809019e0d8f4b3f018f4a7017e8a1

As you can see, although I see a `data-src` attribute that has a `/` URL, I don't see a `src` attribute with one of those... Maybe I'm ending up using different source markup? Or there's some other difference? If you're able to provide more detailed STR that would really help. :-)

**Comment by bittlingmayer** [comment]
Odd.  I wonder if it's because you're in the EU that they try to monetise you.  This is what I see:
<img width="1008" alt="screen shot 2018-05-24 at 22 26 57" src="https://user-images.githubusercontent.com/11457984/40504204-aeb9e5da-5fa1-11e8-82a9-673d92c927c4.png">

**Comment by bittlingmayer** [comment]
Here is my gist.

I thought maybe it was because of our fork, for because I was still passing URL, but apparently not.  I just did a fresh npm install of mozilla/readability and jsdom.  It could be related to using jsdom.

https://gist.github.com/bittlingmayer/b15c5dc36a5a5d533fd693dbf3e4fbee

**Comment by gijsk** [comment]
Sorry for the delay. I just debugged this, and it took me way too long to realize, but the problem is that in your gist, at no point is a URL provided. So the JSDOM DOM has no baseURI (so it becomes `"about:blank"` which can't have relative URIs). If you construct the JSDOM DOM by passing it a `url` option, that includes the original page URI, then it works. :-)

**Comment by gijsk** [comment]
I tried to improve the docs a bit here - https://github.com/mozilla/readability/commit/4b193ccd6addd86d9026dc4fe1f2d12e512e3ee6#diff-04c6e90faac2675aa89e2176d2eec7d8 . Let me know if that is helpful or if you can think of another way of improving the documentation here.

I am a bit hesitant to add an example because it seems like `jsdom` APIs keep changing. For example, I was familiar with their `FetchExternalResources` and `ProcessExternalResources` options in your gist, but they have disappeared from their README, and instead I now see a `runScripts` property (which defaults to false).

**Comment by bittlingmayer** [comment]
Thanks, and sorry for taking your time, I will fix the bug on our end.

I think some explicit error would be good, but maybe there are legitimate cases where URI is `about:blank`?

**Comment by gijsk** [comment]
There might be, but we could add a warning if the document's URI is about:blank and we encounter a relative URI... What would be the best way to surface the errors? Given readability's purpose is essentially about being lenient with input, throwing a JS error and failing to process the document seems a bit extreme. Would stderr have worked for you, or can you think of some other way to do this? @bittlingmayer

**Comment by bittlingmayer** [comment]
Yes, understand the trade-off, we don't want this to be fatal either.  stderr works, we monitor console.error closely enough, if it were happening every time then we would have noticed, assuming we pass `{debug: true}`.
