### ISSUE TITLE
Reading mode doesn't work on these sites

### ISSUE THREAD

**Issue by VoinNochi** [mozilla/readability#465]
Reading mode doesn't appear on sites: [lib.ru](http://lib.ru), [zhurnal.lib.ru](http://zhurnal.lib.ru/), [samlib.ru](http://samlib.ru), [budclub.ru ](http://budclub.ru/)
For example: http://samlib.ru/k/kondratxew_l_w/oe.shtml

**Comment by gijsk** [comment]
These are all variations of the same website, which seems to put all its content into `<dd>` tags. Those are "description lists", see https://developer.mozilla.org/en-US/docs/Web/HTML/Element/dd , so we don't recognize them as reader-able content. I think the simplest thing here would be for the website to adjust how it renders these large bits of text...

**Comment by VoinNochi** [comment]
Could you make opportunity to manually turn on Reading Mode? I'm sure that you thought about it, so I wonder why there is not such feature.

**Comment by gijsk** [comment]
> Could you make opportunity to manually turn on Reading Mode?

Web extensions can do so.

> I'm sure that you thought about it, so I wonder why there is not such feature.

Because it's confusing for users to always show the button, and because the quality of the result varies on sites where reader mode "doesn't make sense", e.g. single-page applications that don't have significant amounts of text besides e.g. error messages stored in off-screen container elements (like, say, Youtube).

> Chrome browser can do so.

Chrome doesn't have reader mode built-in, I think? All the search results I see are for extensions.

**Comment by VoinNochi** [comment]
Thank you!

**Comment by VoinNochi** [comment]
> Chrome doesn't have reader mode built-in, I think? All the search results I see are for extensions.

This was said about mobile version of Chrome. I used it many times before.
