### ISSUE TITLE
byline not extracted for many sites eg medium

### ISSUE THREAD

**Issue by 8enmann** [mozilla/readability#488]
https://medium.com/@pimterry/host-your-node-app-on-dokku-digitalocean-1cb97e3ab041

**Comment by gijsk** [comment]
> Maybe we can [resolve a swathe of byline bugs](https://github.com/mozilla/readability/issues?utf8=%E2%9C%93&q=is%3Aissue+is%3Aopen+byline) 

We already use meta tags, and I wouldn't be surprised if a bunch of those issues are now resolved... it's been a while since anyone's had a chance to take a broom through them.

> by referring to relevant <meta> tags in the head?

In this specific case: Which meta tags? I only see `<meta property="author" ... >` which according to https://github.com/mozilla/readability/pull/478#discussion_r212388935 isn't valid. It may be necessary to re-add support if many sites rely on this, even if it's not technically in a spec somewhere. Maybe @da2x wants to weigh in.

**Comment by danburzo** [comment]
> We already use meta tags, and I wouldn't be surprised if a bunch of those issues are now resolved... it's been a while since anyone's had a chance to take a broom through them.

Oops, sorry. Somehow missed that.

For the original link posted to this thread: https://medium.com/@pimterry/host-your-node-app-on-dokku-digitalocean-1cb97e3ab041 — this regressed in Firefox 63, if that gives you any clue. I coincidentally had 62 up to a few minutes ago, and I could see the byline.

**Comment by gijsk** [comment]
Yes, the change in #478 removed the `<meta property=author` support because of the discussion in the comment I linked to. :-)

**Comment by danburzo** [comment]
Ah, got it. As per [this spec](https://www.w3.org/TR/html5/document-metadata.html#standard-metadata-names) `author` seems to be a valid meta tag, though, so I don't see a problem with reading it. Maybe @da2x can provide some more details on the matter.

**Comment by 8enmann** [comment]
@danburzo I'm a little lost. Anything I can do to help? Is there a path forward?

**Comment by danburzo** [comment]
My proposal, that would fix the problem with Medium articles, is to read the author from:

```html
<meta property="article:author" content="...">
```

The [`article` namespace](http://ogp.me/#type_article) corresponds to the Open Graph protocol.

**Comment by danburzo** [comment]
Ugh, sorry. I was looking at the generated DOM, e.g.

```
document.querySelector('meta[property="article:author"]').content
```

It didn't even cross my mind that someone would alter these tags at run-time...

**Comment by da2x** [comment]
`meta[property="article:author"]` is supposed to contain a URL to a profile (specifically a Facebook profile). It’s not suited to extract the name of the author even though some websites include a name instead of a URL. The spec is clear on that this isn’t supposed to contain a string with the author’s name.

**Comment by da2x** [comment]
This can’t be fixed in a good way because Medium isn’t providing the data in a useful format.

**Comment by danburzo** [comment]
I've just [added basic JSON-LD support](https://github.com/danburzo/percollate/commit/8dc773afc08315f71662db2dd349da28495a971b#diff-c88e1681d3ffeff8d66fbac2d796a53f) to percollate's Readability version. 

Worth noting that for the [original Medium article in this thread](https://medium.com/@pimterry/host-your-node-app-on-dokku-digitalocean-1cb97e3ab041), the current Readability extracts the byline correctly even without JSON-LD.

That being said, JSON-LD seems mostly (but not entirely) superior:

* On [Wikipedia pages](https://en.wikipedia.org/wiki/JSON-LD) we get a nicer name and byline: _JSON-LD, By Contributors to Wikimedia projects_ vs. _JSON-LD - Wikipedia_.
* On [Medium articles](https://medium.com/@pimterry/host-your-node-app-on-dokku-digitalocean-1cb97e3ab041), the Schema.org article title includes the author's and the publisher's name: _Host your Node app on Dokku & DigitalOcean - Tim Perry - Medium_.
* On [other articles](https://www.fastcompany.com/3053406/how-apple-is-giving-design-a-bad-name), using JSON-LD results in nicer bylines: _By Don Norman and Bruce Tognazzini_ rather than _By By Don Norman and Bruce Tognazzinilong Read_.

**Comment by gijsk** [comment]
Given that we have JSON-LD support now, let's close this out, and we can open new issues for any remaining places where we do not get the right info.
