### ISSUE TITLE
Readability throws error during parse - Readability._isProbablyVisible - `TypeError: Cannot read property 'display' of undefined` - due to MathML

### ISSUE THREAD

**Issue by 8enmann** [mozilla/readability#493]
Site: https://www.gwern.net/Morning-writing

Stack trace:
```
Uncaught (in promise) TypeError: Cannot read property 'display' of undefined
    at Readability._isProbablyVisible (<anonymous>:1:159030)
    at Readability._grabArticle (<anonymous>:1:141785)
    at Readability.parse (<anonymous>:1:160308)
    ....
```

**Comment by gijsk** [comment]
Can you provide a more complete testcase? That is, how are you passing this through readability? The stack information suggests you're minifying stuff in a way that makes it impossible to figure out from the stack alone what's going on here...

(The page parses fine in reader mode in Firefox...)

**Comment by 8enmann** [comment]
I get the same error on Node
https://github.com/8enmann/readability-proxy
`npm install`
`npm start`
visit http://localhost:3000/?url=https://www.gwern.net/Morning-writing
```
TypeError: Cannot read property 'display' of undefined
    at Readability._isProbablyVisible (/Users/ben/Documents/readability/node_modules/readability/Readability.js:1704:23)
    at Readability._grabArticle (/Users/ben/Documents/readability/node_modules/readability/Readability.js:776:19)
    at Readability.parse (/Users/ben/Documents/readability/node_modules/readability/Readability.js:1795:31)
    at parse (/Users/ben/Documents/readability/index.js:53:54)
    at <anonymous>
```

**Comment by 8enmann** [comment]
Ping

**Comment by gijsk** [comment]
I don't know why this would happen off-hand - there's a nullcheck on `node`, and it's not clear to me why `node.style` would ever be `undefined` in this case. I don't have cycles to debug this myself at the moment.

**Comment by danburzo** [comment]
This sounds like this could be a bug in how `jsdom` parses the web page, since it seems to be working correctly in Firefox Reader View.

**Comment by gijsk** [comment]
Hm, well, it's possible that we get different content in this case (UA sniffing, for instance), and I guess in theory it's possible that `node` ends up being the `document` node (not `documentElement`, just `document`) which won't have a style property. But I don't know why that'd happen, and that'd be the root cause here - while we could wallpaper this particular exception, that wouldn't actually help the wider issue. It is definitely also possible there's a `jsdom` bug...

**Comment by danburzo** [comment]
Ok, here's the problem. Either `jsdom` or `readability` chokes on MathML:

```xml
<math display="inline" xmlns="http://www.w3.org/1998/Math/MathML">
	<semantics><mrow><mn>0.10</mn><mo>⋅</mo><mn>20</mn><mo>⋅</mo><mn>121</mn><mo>=</mo><mi>$</mi><mn>242</mn></mrow><annotation encoding="application/x-tex">0.10\cdot 20 \cdot 121 = \$242</annotation></semantics></math>
	<semantics><mrow><mn>0.10</mn><mo>⋅</mo><mn>20</mn><mo>⋅</mo><mn>121</mn><mo>=</mo><mi>$</mi><mn>242</mn></mrow><annotation encoding="application/x-tex">0.10\cdot 20 \cdot 121 = \$242</annotation></semantics>
	<mrow><mn>0.10</mn><mo>⋅</mo><mn>20</mn><mo>⋅</mo><mn>121</mn><mo>=</mo><mi>$</mi><mn>242</mn></mrow>
	<mn>0.10</mn>
	<mo>⋅</mo>
	<mn>20</mn>
	<mo>⋅</mo>
	<mn>121</mn>
	<mo>=</mo>
	<mi>$</mi>
	<mn>242</mn>
	<annotation encoding="application/x-tex">0.10\cdot 20 \cdot 121 = \$242</annotation>
```

It works in Firefox Reader View because it's converted to HTML via MathJAX.

**Comment by danburzo** [comment]
Here's a page containing some MathML examples: https://www.freedomscientific.com/content/html/jawshq/MathML-Samples.html
In Firefox and Chrome, the style attribute on the <math> object is undefined — I assume that is because the Document Object Model for embedded MathML is not documented and incompletely implemented in browsers. I do believe, in this case, Readability can benefit from checking the existence of the `style` attribute, since it seems there are cases where it's missing.

**Comment by gijsk** [comment]
@danburzo thanks for figuring that out. It looks like this is the only `.style` access in the code at the moment, so in this case perhaps it's enough to change the conditional at https://github.com/mozilla/readability/blob/master/Readability.js#L1704 to check if `style` is truthy before trying to access its `display` property. Would you be able to do a PR for that?

**Comment by danburzo** [comment]
@gijsk please see the PR above. I considered elements without style to be _theoretically_ visible. Tested the change in [percollate](https://github.com/danburzo/percollate), and the PDF is generated correctly inasmuch as Chromium supports MathML (that is, does not, in this case).

**Comment by 8enmann** [comment]
Thanks!!
