### ISSUE TITLE
Reader view only shows first story on page

### ISSUE THREAD

**Issue by mikedanger** [mozilla/readability#495]
https://www.howard-winn.k12.ia.us/crestwood-secondary-home/parentsstudents-information/hs-accouncements

Anything we can do to correct this? (I'm on the support team for their CMS.) I suspect this is essentially the same as/similar to https://github.com/mozilla/readability/issues/473 but I wanted to do my due diligence. :)

**Comment by gijsk** [comment]
> https://www.howard-winn.k12.ia.us/crestwood-secondary-home/parentsstudents-information/hs-accouncements
> 
> Anything we can do to correct this? (I'm on the support team for their CMS.)

Not really, no. If you want to correct this from the CMS side you could try ensuring the weighting of the container of all the announcements is higher, by giving it more of the ids/classes that reader mode looks for ( https://github.com/mozilla/readability/blob/44e90de00bc14659f70d9a6c49bf8c071a08b766/Readability.js#L116 ). That's pretty hacky, but should work. You can see what's going on by flipping the debug switch to true at https://github.com/mozilla/readability/blob/44e90de00bc14659f70d9a6c49bf8c071a08b766/Readability.js#L45 , when running in node js.

> I suspect this is essentially the same as/similar to #473 but I wanted to do my due diligence. :)

Yep. I'll close this because there isn't really a generic thing Readability can do here. It's hard to optimize for this situation to include more than 1 article (which still won't please some people on the infinite scrolling case) without then also going wrong in cases where articles have large lists of "you may want to read this next" content. :-(

**Comment by mikedanger** [comment]
Totally understand, thanks for taking a look!
