### ISSUE TITLE
document the install procedure

### ISSUE THREAD

**Issue by SvetlanaTkachenko** [mozilla/readability#533]
how to install using npm ( nodejs ); how to install for usage from javascript - please add this to the documentation

**Comment by gijsk** [comment]
There's no npm package atm (see #43 ). I don't think adding instructions for using github to install it is useful - hopefully we can sort out the NPM situation soon instead. Otherwise, people just end up stuck on old versions of the package sourced via github (or use `master` and get constant breakage, or something).

For non-node envs, there's no real "installation"... you load the script file the same way you load any other script file, and then you use it as described in the docs, so I don't see what other explanations are needed...

**Comment by SvetlanaTkachenko** [comment]
Thank you for describing the situation. I am glad there will be an npm version possible soon.

How do I install the stable version today? Could you please provide me with installation instructions that work at the current time?

**Comment by gijsk** [comment]
https://medium.com/@jonchurch/use-github-branch-as-dependency-in-package-json-5eb609c81f1a may be helpful.

There isn't a stable version today; If you're experimenting with things I'd suggest either using master as the branch tag and accepting breakage, or picking the current revision and updating when necessary/desired.

**Comment by SvetlanaTkachenko** [comment]
@gijsk 

I don't have package.json, which makes the article you linked more confusing.

I am looking for the same 'stable' version as ships with Firefox for its reading view.

I face confusion here. I understand that 'master' includes breakage, but I don't see what is the definition of 'current revision', or how to use it.

**Comment by gijsk** [comment]
I don't know how to help, sorry. The `npm install` instruction at the top of the article seems like it should work, irrespective of whether you have a package.json . If it doesn't, I don't know enough about npm to help.

For the "stable" version that ships with Firefox - we import from 'master' on this repository, and fix any issues that come up. The latest import (that will ship with Firefox 67) is from what is 'master' a few days ago, see https://bugzilla.mozilla.org/show_bug.cgi?id=1531712 . (Compared to current 'master', we're only missing a test-only commit, ie https://github.com/mozilla/readability/commit/cb5771fd4a832bf257bf1b86f7fbdcb74068d3c5 .
