### ISSUE TITLE
How the FF ReaderMode configures Readability?

### ISSUE THREAD

**Issue by Ahmed-Ali** [mozilla/readability#572]
I am a bit confused; in ReaderMode in Firefox the parsing of this wiki page: https://en.wikipedia.org/wiki/List_of_typefaces_included_with_macOS

is different than what the Readability.parse method would return. So I wonder if there is anything special the ReaderMode does to configure the Readability differently?

I noticed only a set of "classes to preserver": https://dxr.mozilla.org/mozilla-central/rev/66a1c07a8f48c5129aa3867813bacb6e7ef22d8c/toolkit/components/reader/ReaderMode.jsm#21-32

But not sure if that's all? and if so, why the result is different than what in Readability master branch?

Thank you

**Comment by Ahmed-Ali** [comment]
Seems like ReaderMode doesn't always use the same configurations/algorithm.
I wonder what is the difference between the first run and subsequent refreshes (after the refresh the content is similar to what Readability produces)
![FF-ReaderMode](https://user-images.githubusercontent.com/5157350/71711046-0f97cc80-2df7-11ea-917c-c2a02358289c.gif)

**Comment by gijsk** [comment]
This isn't an actual issue with readability, so I'm going to close this.

I don't know what difference you're looking at. The classes are the only option we're passing, see https://searchfox.org/mozilla-central/rev/053826b10f838f77c27507e5efecc96e34718541/toolkit/components/reader/ReaderMode.jsm#469-473 (passed through to https://searchfox.org/mozilla-central/rev/053826b10f838f77c27507e5efecc96e34718541/toolkit/components/reader/ReaderWorker.js#51-53 ). Any other difference you're seeing may be because we're parsing from the serialized document when the document is loaded and you click the "enter reader mode" button (so this will normally be after page JS has had a chance to run). If you refresh reader mode, we will use an XHR/fetch call to get the page, and use the document that returns - which means no JS runs at all. The documents are often different, for better or for worse.

**Comment by Ahmed-Ali** [comment]
Apologies for the confusion, it is not an issue with readability, yes. I just didn't know where is the best channel to ask. (Any pointer for future reference will be great).

So if I understand correctly, the initial run, is just rendering the result from the XMLSerializer of the doc; after the refresh, this is potentially the final result from calling Readability, right?

**Comment by gijsk** [comment]
No, both of them are the result of running Readability. They're just running readability on different source documents.

The initial run is on the currently-shown document (ie the wikipedia page which at that point has run a bunch of scripts that change the DOM, because it was rendered in the browser).

After refreshing reader mode, we no longer have access to that document (it wasn't shown when reader mode was entered the second time) and so we have to fetch the original document over the network using fetch/XHR, parse it into a new DOM - and crucially, we do not render it or run scripts. This means that DOM is different from the DOM we used the first time.

**Comment by Ahmed-Ali** [comment]
Got ya! Thanks a lot, that makes sense!
This was driving me crazy as in my usage I do fetch the document and parse without rendering, so it was deriving me bit crazy :)
