### ISSUE TITLE
Readability freezes with 100% CPU on specific URL

### ISSUE THREAD

**Issue by zdila** [mozilla/readability#580]
```typescript
import jsdom from 'jsdom';
import Readability from 'mozilla-readability';

const url = 'https://www.sec.gov/Archives/edgar/data/1794515/000162828020002344/zoominfos-1.htm';

jsdom.JSDOM.fromURL(url, {
  resources: new jsdom.ResourceLoader()
}).then(doc => {
  const reader = new Readability(doc.window.document);

  return reader.parse(); // this freezes @ 100% CPU
});
```

Node.js 12
jsdom 16.1.0

**Comment by gijsk** [comment]
> import Readability from 'mozilla-readability';

What version of readability? We don't ship any public packages (yet).

**Comment by zdila** [comment]
In `package.json` we have:
```
"dependendies": {
  "mozilla-readability": "git+https://github.com/mozilla/readability.git",
  ...
}
```

**Comment by gijsk** [comment]
I'm sorry but how do I run your example, exactly? It doesn't run in the nodejs interpreter because of the ES import syntax, and I haven't used ES modules with nodejs before so I'm spending way too much time just guessing at how to replicate what you're doing.

**Comment by zdila** [comment]
No problem, I will prepare a testcase today or tomorrow :-)

**Comment by gijsk** [comment]
OK, I can reproduce with:

```js
let { JSDOM, ResourceLoader } = require('jsdom');
var { Readability } = require('../readability/index');

const url = 'https://www.sec.gov/Archives/edgar/data/1794515/000162828020002344/zoominfos-1.htm';

JSDOM.fromURL(url, {
  resources: new ResourceLoader()
}).then(doc => {
  const reader = new Readability(doc.window.document);

  return reader.parse(); // this freezes @ 100% CPU
});
```

If I use the profiler/debugger, it seems we get stuck in some kind of loop inside `_prepDocument` which tries to replace all `font` tags with `span`s. It does this on the result of a `getElementsByTagName`, which is a live collection, and it seems `jsdoc` *really* doesn't like this. I haven't done a detailed profile of what's going on, but I think because we re-evaluate the `length` and index into the list, and because it gives a Proxy object of some kind, it keeps re-producing that list. And the list has 15570 elements (this seems correct, I get the same result loading the document in the browser). So that doesn't go well...

**Comment by gijsk** [comment]
I've put up a patch that I believe addresses the issue. It's still not super fast - but then, it's a large document so that's not entirely surprising...

**Comment by zdila** [comment]
Oh, I've just temporarily switched to `node-readability` :-). But I will your fix soon. Thanks!
