### ISSUE TITLE
Question on `hasChildBlockElement`

### ISSUE THREAD

**Issue by hipstermojo** [mozilla/readability#625]
I noticed that the function checks whether any child node has a tag name matching those in the `DIV_TO_P_ELEMS` array. One of these elements is the `<a>` tag which is actually an inline element. Was this intentional?

**Comment by gijsk** [comment]
Well, the code has been like that since 6 years ago when it was imported to github, so probably since the original arc90 version of this. So it's hard to say what the "intent" of other people, all those years ago, was - the comments don't really tell us. :-(

@hipstermojo Out of interest, how did you run into this? It's easier to see we should change it if it's breaking something in particular. :-)

**Comment by gijsk** [comment]
(It looks like dropping "A" from the list has 0 impact across all of the testcases.)

**Comment by hipstermojo** [comment]
I ran into this "realization" while porting this library to Rust. I haven't finished porting it so I don't how how differently the code will run once I write it slightly differently from what is in the "canonical" implementation in this repository.

I opted to be more formal and just compare elements with the full list of block elements since I saw that even `<img>` and `<select>` are not block elements.

**Comment by hipstermojo** [comment]
I've tested it out and it does break quite a lot of tests lol. I will try investigating why. The time taken to run tests is much longer, probably because searching for a tag name in the array runs at n time and using a Set would be more efficient. In any case, would it mean the test suite should be changed?

**Comment by gijsk** [comment]
I'm a little confused - what specifically breaks tests? Swapping the list out for a list of actual block elements per the spec? Because just removing `"A"` didn't affect test output...

As for the time taken to run tests being longer, that could also be a result of different outcomes meaning we spend more time in other parts of the code...

Using a `Set` is a good idea though I don't know if those are guaranteed to be available in the version of node the library requires...

**Comment by hipstermojo** [comment]
I meant swapping it for a list of actual block elements as per the spec.

> Using a Set is a good idea though I don't know if those are guaranteed to be available in the version of node the library requires...
I feared as much :(

**Comment by hipstermojo** [comment]
Would it be okay to open other issues on some of the things that can also be safely removed from the codebase for easier readability? (excuse the pun)

**Comment by gijsk** [comment]
Sure, I'd be more than happy with some issues and/or PRs around things that, on closer inspection, look useless / broken to you. Thank you for sharing that knowledge!

**Comment by hipstermojo** [comment]
Alright. Sounds great :smile: . I'll just close this then and hopefully get a PR out when I'm done porting as much as I can
