### ISSUE TITLE
Block reader mode

### ISSUE THREAD

**Issue by humbertorodrigues** [mozilla/readability#644]
It's possible block this feature on my website? Some page I would like to not allow the reader mode.

**Comment by gijsk** [comment]
A few notes:

1. this tracker is for the library used by reader mode - not reader mode the Firefox feature as a whole.
2. the goal of both the feature and the library is to extract the salient information from a given webpage
3. we do not support an explicit "block reader mode" option in either Firefox or the library
4. if we did, someone would create a fork of all this open source code that didn't honour that option before you could say "but copyright"
5. other browsers have similar tools with different algorithms
6. this tool and others like it are important for users of assistive technology, who cannot otherwise consume the web content in question at all, because the original content causes them to experience migraines, seizures, or other serious issues, or because they simply cannot perceive it otherwise. Please reconsider your intent to block the feature entirely.
