### ISSUE TITLE
Reader View is almost nonexistent on aljazeera.com 

### ISSUE THREAD

**Issue by Xashyar** [mozilla/readability#656]
I'm not sure if it's a DRM-related issue or it's because of the websites recent migration to React.js. 
in either case, this is true on all platforms.

e.g.:
~~https://www.aljazeera.com/news/2006/10/25/firefox-web-browser-update-released~~

**Comment by gijsk** [comment]
>  https://www.aljazeera.com/news/2006/10/25/firefox-web-browser-update-released

I'm confused - this example works for me (Firefox 84 beta).

Can you elaborate on what's broken, and on what browser and version of that browser you're testing?

**Comment by Xashyar** [comment]
> I'm confused - this example works for me (Firefox 84 beta).

I'm confused here as well, it didn't show up at the time of filing (now it even appears for Firefox 83.0).

Reader View is arbitrarily and rarely available on the website, I suggest exploring any other page on there. 99% of the times it won't appear.

**Comment by gijsk** [comment]
I think this is a Firefox bug about when it checks to see if the page is readerable - it seems to have to do with navigating the webpage. If you then refresh, the reader mode icon shows up. Because this isn't an issue with the readability library itself, I've filed https://bugzilla.mozilla.org/show_bug.cgi?id=1681916 against Firefox, and I'll close this issue.
