### ISSUE TITLE
We shouldn't strip tables agressively, as they're most often actually part of content

### ISSUE THREAD

**Issue by n1k0** [mozilla/readability#66]
Tabular data are valid content and shouldn't be stripped out entirely. If we're afraid of websites using tables as a layout strategy, once the main article content is properly identified that shouldn't be an issue.

Sample example: https://hsivonen.fi/webm-share/

**Comment by EraYaN** [comment]
Here is another example https://factorio.com/blog/post/fff-282 (All blog posts on this blog).

**Comment by RadhiFadlillah** [comment]
I've also experienced this issue with https://www.csie.ntu.edu.tw/~cjlin/libsvm/index.html

The problem is happened because in [`_cleanConditionally`](https://github.com/mozilla/readability/blob/master/Readability.js#L1619) we only check if the `node` is inside data table, but we didn't check if the `node` itself is data table.

**Comment by gijsk** [comment]
I've confirmed that the originally reported page as well as the one from https://github.com/mozilla/readability/issues/66#issuecomment-464205346 now work.

**Comment by PalmerAL** [comment]
@gijsk It looks like the table headers from https://factorio.com/blog/post/fff-282 are still being removed, I'm guessing that's not supposed to happen?

**Comment by RadhiFadlillah** [comment]
@PalmerAL good catch, I missed that while making the PR.

The table headers are removed because their class name is `header_cell`, which got caught by [`REGEXPS.unlikelyCandidates`](https://github.com/mozilla/readability/blob/master/Readability.js#L117). To fix it, we can either :
- modify the regular expression, or
- exclude table-related tags (in this case `td`) while removing the unlikely elements in this [line](https://github.com/mozilla/readability/blob/master/Readability.js#L804).

I think the latter is safer. If so, how many tags should we exclude ? 

Should we only exclude `td`, or exclude other table-content tag like `td`, `th` and `tr` ?

**Comment by gijsk** [comment]
> 
> 
> @PalmerAL good catch, I missed that while making the PR.
> 
> The table headers are removed because their class name is `header_cell`, which got caught by [`REGEXPS.unlikelyCandidates`](https://github.com/mozilla/readability/blob/master/Readability.js#L117). To fix it, we can either :
> 
>     * modify the regular expression, or
> 
>     * exclude table-related tags (in this case `td`) while removing the unlikely elements in this [line](https://github.com/mozilla/readability/blob/master/Readability.js#L804).
> 
> 
> I think the latter is safer.

I concur.

> If so, how many tags should we exclude ?
> 
> Should we only exclude `td`, or exclude other table-content tag like `td`, `th` and `tr` ?

You can use `_hasAncestorTag` and check for a `table` ancestor, I think? Thanks for picking this up!

**Comment by gijsk** [comment]
@RadhiFadlillah should I file a new issue for the header stuff or will you be doing a PR separately anyway?

**Comment by RadhiFadlillah** [comment]
@gijsk I think there is no need to create new issue. 

I will create separate PR later after I done with #526.
