### ISSUE TITLE
Video regex should be configurable to allow videos from other sites to be retained in readability output

### ISSUE THREAD

**Issue by cgorrieri** [mozilla/readability#787]
There seems to be some discrimination on the URL of the iframes as I found this regex https://github.com/mozilla/readability/blob/8e8ec27cd2013940bc6f3cc609de10e35a1d9d86/Readability.js#L133. I think this should be configurable as I would want more video sources.

The 2 tests below should both pass, but the second one fails and the iframe is completely removed from the result.

```js
it('should keep youtube iframe ', async () => {
  const html =
    '<p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed ac nisi tincidunt, laoreet risus ac, molestie sem.</p>' +
    '<iframe src="//www.youtube.com/embed/RT7TSi0hbTM" allowfullscreen=""></iframe>';

  const dom = new JSDOM(html);
  const readable = new Readability(dom.window.document, {
    charThreshold: 20,
  }).parse();

  expect(readable?.content).toEqual(`<div id="readability-page-1" class="page">${html}</div>`);
  // PASS
});

it('should keep gifycat iframe', async () => {
  const html =
    '<p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed ac nisi tincidunt, laoreet risus ac, molestie sem.</p>' +
    '<iframe src="//gfycat.com/ifr/generousoccasionalfirecrest" allowfullscreen=""></iframe>';

  const dom = new JSDOM(html);
  const readable = new Readability(dom.window.document, {
    charThreshold: 20,
  }).parse();

  expect(readable?.content).toEqual(`<div id="readability-page-1" class="page">${html}</div>`);
  /* FAILS
    Expected: "<div id=\"readability-page-1\" class=\"page\"><p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed ac nisi tincidunt, laoreet risus ac, molestie sem.</p><iframe src=\"https://gfycat.com/ifr/generousoccasionalfirecrest#?secret=sMg8AHCe0d\" allowfullscreen=\"\"></iframe></div>"
    Received: "<div id=\"readability-page-1\" class=\"page\"><p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed ac nisi tincidunt, laoreet risus ac, molestie sem.</p></div>"
  */
});
```

**Comment by gijsk** [comment]
"discrimination" is maybe not the most helpful word here. But yes, the types of frames that are loaded are restricted, primarily because we don't want ad frames included in the readability output. I don't see a good way of avoiding that without the use of some kind of list of acceptable frame URLs. I think removing frames by default is the right default (rather than allowing them by default and removing ad frames, which is a much larger set than video frames).

I'd be happy to take a patch with a test that allows consumers to specify alternative regexes. It's a little moot for Firefox as its sandboxing and anti-XSS sanitization rules will remove any iframes we keep anyway.

**Comment by cgorrieri** [comment]
PR created https://github.com/mozilla/readability/pull/788

**Comment by cgorrieri** [comment]
Thank you for the merge! When do you think we can release a new version?

**Comment by gijsk** [comment]
I'm hoping for the coming week. Today is a day off for all of Mozilla, so I'm planning on coming back to this on Monday.
