### ISSUE TITLE
Crashes on all Pinterest and many other websites, minimal reproduction

### ISSUE THREAD

**Issue by koresar** [mozilla/readability#836]
```js
const html = `
<div><div><div>
More than 25 characters!!
</div></div></div>
<div><meta name="twitter:title" content="1"></div>`;

const doc = new DOMParser().parseFromString(html, 'text/html')
const base = doc.createElement('base')
base.setAttribute('href', url)
doc.head.appendChild(base)
const reader = new Readability(doc, {
    keepClasses: true,
})

const result = reader.parse(); // crashes here
```

Stack trace:

```
TypeError: Cannot read properties of null (reading 'tagName')
    at Readability._grabArticle (node_modules/@extractus/article-extractor/node_modules/@mozilla/readability/Readability.js:1147:37)
    at Readability.parse (node_modules/@extractus/article-extractor/node_modules/@mozilla/readability/Readability.js:2265:31)
```

Pages to test on:
* https://www.pinterest.ca/variamsingh87/
* https://www.pinterest.com.au/seriako/

I couldn't fix myself. Sorry.

**Comment by gijsk** [comment]
@koresar Thanks for the report. What environment do you run your minimal testcase in? In `nodejs`, it produces `DOMParser` is not defined errors.

For the pinterest urls, I see that readability doesn't output anything (when running `npm run generate-testcase pinterest "https://www.pinterest.ca/variamsingh87/"`) but I don't see "crashes". Are you sure it's the same problem?

**Comment by koresar** [comment]
Apologies @gijsk 
I forgot to bring more details.

That's Node.js. All Readability versions affected (I tried them all).

```sh
npm i @mozilla/readability linkedom
```

test.mjs:

```js
import { Readability } from "@mozilla/readability";
import { DOMParser } from "linkedom";

const url = "https://www.pinterest.ca/variamsingh87/";
const html = `
<div><div><div>
More than 25 characters!!
</div></div></div>
<div><meta name="twitter:title" content="1"></div>`;

const doc = new DOMParser().parseFromString(html, "text/html");
const base = doc.createElement("base");
base.setAttribute("href", url);
doc.head.appendChild(base);

const reader = new Readability(doc, {
  keepClasses: true,
});
const result = reader.parse() ?? {};

console.log(result.textContent ? result.content : null);
```

Reading your comment I am starting to think that it's the `linkedom` bug. :(

**Comment by gijsk** [comment]
No worries. It's possible it's a `linkedom` problem. I'm a bit swamped at the moment and don't have a lot of time to look myself - if it's easy for you to check, you could see if the same thing happens if you run the same testcase but use `DOMParser` from `jsdom`? That would help narrow down the problem.

`linkedom` has a very... opinionated... approach to the DOM, and basically claims that it'd be better if some DOM mechanisms worked differently in order to improve performance. It requires consumers to not rely in any way on those DOM mechanisms working the way the browsers, `jsdom` and the spec say they do (and in exchange, in principle performance should be better). We've previously fixed some issues with `linkedom` compatibility and if it's straightforward to do so here I would be open to doing it, but we'd need to understand a bit more what exactly is happening differently with `linkedom` vs all the other DOM implementations.

**Comment by koresar** [comment]
Looks like it doesn't make much sense to fix linkedom issues in readability. Closing now.
Thank you!

**Comment by SettingDust** [comment]
After some research. It's caused by the input HTML. https://github.com/WebReflection/linkedom/issues/147
As linkedom side points out, you need to wrap your element in the body.
The input in your example(https://github.com/mozilla/readability/issues/836#issue-2089560070) will be parsed to html like below 
```js
`
<div><head><base href="https://www.pinterest.ca/variamsingh87/"></head><body></body><div><p>
More than 25 characters!!
</p></div></div>
<P><meta name="twitter:title" content="1"></P>`
```
So that readability won't accept that since the body isn't actual body

**Comment by SettingDust** [comment]
But for Pinterest it's a bit different. I doubt readability can handle it properly.
![图片](https://github.com/mozilla/readability/assets/19922286/661146d1-c3ae-4ad7-b537-956d8ad3ce73)
