### ISSUE TITLE
Add the "simple check" script to the repo

### ISSUE THREAD

**Issue by DavidBruant** [mozilla/readability#85]
From #77 
> Note that on Android we ran this parse on every page load (to see if it was worth/possible offering reader mode), and we couldn't manipulate the real DOM because that'd obviously change the page, so there was a need to serialize+reparse anyway.

> We don't do that anymore on desktop because doing that caused a boatload of perf regressions. So we have a simpler check that determines whether we show the button, which isn't 1:1 equivalent to whether the content is reader-able, but it's close. From that perspective, in principle we could reuse the DOM.

If Mozilla came to the conclusion that Readability is only practical if a simple check is used beforehand (instead of running readability on every page), I believe it might be worth adding this simpler check to this repo.
This will help other reusers too (including the iOS browser as I understand it).

**Comment by leibovic** [comment]
I think this is a good point (/cc @st3fan @thebnich). We don't do this in Firefox for Android yet, but we will probably do this soon to match desktop (https://bugzilla.mozilla.org/show_bug.cgi?id=1046112#c10).

Right now this code lives in ReaderMode.jsm, which is a module shared between desktop/Android Firefox:
http://mxr.mozilla.org/mozilla-central/source/toolkit/components/reader/ReaderMode.jsm?force=1#70

There's also a bug filed about trying to make this method better, since it's currently a bit aggressive about saying pages aren't reader-able:
https://bugzilla.mozilla.org/show_bug.cgi?id=1147626

**Comment by leibovic** [comment]
Yes, definitely, I want some tests for this. I could make a PR for this.

@n1k0, do you have ideas about where we should put this? Should it just go in its own file? The annoying bit about that would be trying to keep that in sync with our version in mozilla-central.

Alternately, we could make another method on the Readability object, but then we would need to update ReaderMode.jsm to import Readability.js. But I assume that's not a big deal.

**Comment by n1k0** [comment]
> Alternately, we could make another method on the Readability object, but then we would need to update ReaderMode.jsm to import Readability.js. But I assume that's not a big deal.

If it's not a big deal, I think that's the way to go :)

**Comment by n1k0** [comment]
Fixed by #96
